---
name: Automerge
on:
  workflow_call:
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Fetch main
        run: |
          git remote -v
          git fetch --depth=1 origin main
      - name: Only allow go.mod, go.sum, *.gen.go files
        run: |
          find . -type f ! -name 'go.mod' ! -name 'go.sum' ! -name '*.yaml' ! -name '*.yml' ! -name '*.txt' ! -name '*.md' ! -name '*.conf' -exec git diff --exit-code origin/main -- {} +
      # TODO: remove this step when https://github.com/ridedott/merge-me-action/issues/1581 will be resolved
      - name: workaround-graphql-authz
        id: workaround-graphql-authz
        continue-on-error: true
        run: |
          GITHUB_REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
          BRANCH_QUERY='{ repository(name: "GITHUB_REPOSITORY_NAME", owner: "GITHUB_REPOSITORY_OWNER") { branchProtectionRules(first: 10) { edges { node { id } } } } }'
          BRANCH_QUERY=${BRANCH_QUERY/GITHUB_REPOSITORY_NAME/${GITHUB_REPOSITORY_NAME}}
          BRANCH_QUERY=${BRANCH_QUERY/GITHUB_REPOSITORY_OWNER/${GITHUB_REPOSITORY_OWNER}}
          GRAPH_QUERY=$(jq -n --arg q "$(echo $BRANCH_QUERY | tr -d '\n')" '{ query: $q}')
          curl -X POST \
          -si \
          -H "Accept: application/vnd.github.package-deletes-preview+json" \
          -H "Content-Type: application/json" \
          -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
          --data "$GRAPH_QUERY" \
          --url https://api.github.com/graphql
      - name: Merge PR
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: nsmbot
          ENABLED_FOR_MANUAL_CHANGES: true
          GITHUB_TOKEN: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
          MAXIMUM_RETRIES: 25
