---
name: Check release branch
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout networkservicemesh/deployments-k8s
        uses: actions/checkout@v2
        with:
          path: networkservicemesh/deployments-k8s
          repository: networkservicemesh/deployments-k8s
          token: ${{ secrets.token }}

      - name: check-release-branch
        working-directory: networkservicemesh/deployments-k8s
        run: |
          echo Starting to check release branch in deployments-k8s repository
          branch=release/${{ inputs.tag }}
          echo branch to be checked - ${branch}

          if ! [ -z "$(git ls-remote --heads origin ${branch})" ]; then
            echo Branch ${branch} is already presented in deployments-k8s repository
            exit 0;
          fi

          echo Branch ${branch} is not presented in repository
          echo Starting to create ${branch} branch in deployments-k8s repository

          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git checkout -b ${branch}
          git push -u origin ${branch} || exit 0;
