---
name: Exclude Replace in go.mod
on:
  workflow_call:
jobs:
  excludereplace:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Exclude replace in go.mod
        run: |
          grep ^replace go.mod || exit 0
          exit 1
