---
name: Release
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: refs/heads/${{github.event.workflow_run.head_branch}}
      - name: Push tag ${{ inputs.tag }}
        run: |
          git status
          git tag ${{ inputs.tag }}
          git push origin ${{ inputs.tag }} -f
      - name: Create release ${{ inputs.tag }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: refs/tags/${{ inputs.tag }}
          release_name: ${{ inputsinputs.tag }}
          draft: false
          prerelease: false
  