---
name: Release deployments-k8s
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deployments-k8s
        uses: actions/checkout@v4
        with:
          repository: Ex4amp1e/deployments-k8s
          token: ${{ secrets.token }}

      - name: Push update to the deployments-k8s
        # This option makes script continue execution even if some commands return non-zero exit code
        shell: bash {0}
        run: |
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"

          branch=release/${{ inputs.tag }}
          git checkout -b $branch
          git push origin $branch

          if [ "$?" != 0 ]; then
            gh workflow run check-tag.yaml -f branch=$branch --ref=$branch --repo Ex4amp1e/deployments-k8s
          fi
        env:
          GH_TOKEN: ${{ secrets.token }}
