---
name: Release deployments-k8s
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
      token:
        required: true
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
          repository: ${{ github.repository }}

      - name: Create commit message
        working-directory: ${{ github.repository }}
        run: |
          echo "Update docker images to the latest tag ${{ inputs.tag }}" >> /tmp/commit-message
          echo "" >> /tmp/commit-message
          echo "Commit Message:"
          cat /tmp/commit-message

      - name: Checkout networkservicemesh/deployments-k8s
        uses: actions/checkout@v2
        with:
          path: networkservicemesh/deployments-k8s
          repository: networkservicemesh/deployments-k8s
          token: ${{ secrets.token }}
          ref: release/${{ inputs.tag }}

      - name: Find and Replace ci/${{ github.repository }} version
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "ci/${{ github.event.repository.name }}:.*\n"
          replace: "${{ github.event.repository.name }}:${{ inputs.tag }}\n"

      - name: Push update to the deployments-k8s
        working-directory: networkservicemesh/deployments-k8s
        run: |
          echo Starting to update repositotry deployments-k8s
          git add -- .
           if ! [ -n "$(git diff --cached --exit-code)" ]; then
            echo Repository already up to date
            exit 0;
          fi

          branch=release/${{ github.repository }}/${{ inputs.tag }}
          git config --global user.email "nsmbot@networkservicmesh.io"
          git config --global user.name "NSMBot"
          git commit -s -F /tmp/commit-message
          git checkout -b ${branch}
          git push -f origin ${branch}
