---
name: Shell check
on:
  workflow_call:
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shellcheck
        uses: fkautz/shell-linter@v1.0.1
