---
name: Yamllint
on:
  workflow_call:
    inputs:
      config_file:
        type: string
        default: .ci/yamllint.yml
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: ${{ inputs.config_file }}
          strict: true
